services:
  postgres:
    image: timescale/timescaledb:latest-pg17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: live_dashboard_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 30s

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  live_dashboard:
    build:
      context: ./live_dashboard
      dockerfile: Dockerfile
    container_name: live_dashboard
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: ecto://postgres:postgres@postgres:5432/live_dashboard_dev
      PHX_HOST: localhost
      PORT: 4000
      SECRET_KEY_BASE: ${SECRET_KEY_BASE:-vffTTH35S9/LFbOFPSSs3GNuvVxEmFNT6DKgjW0D21PW0GK3Ums7N9xT0opaajN3}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  data_processing:
    build:
      context: ./data_processing
      dockerfile: Dockerfile
    container_name: data_processing
    ports:
      - "8080:8080"
    environment:
      HOST: 0.0.0.0
      PORT: 8080
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  faster-whisper:
    image: fedirz/faster-whisper-server:latest-cpu
    container_name: faster_whisper
    environment:
      - WHISPER_MODEL=base
    volumes:
      - whisper_data:/root/.cache/huggingface
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin-data:
  whisper_data:
